# Generated by Django 3.0.5 on 2020-04-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockItem',
            field=models.CharField(max_length=40),
        ),
    ]
